spring.application.name=backend

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/feedback_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Rakesh@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=86400000

# Logging Configuration
logging.level.com.feedback.backend=DEBUG
logging.level.org.springframework.security=DEBUG
